version: '2'
services:
 node:
   image: vulhub/node:9.0.0
   depends_on:
    - db
   ports:
    - "8080:8080"
 db:
   image: postgres:9.6
   environment: 
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=example
