version: '2'
services:
  web:
    build: .
    ports:
    - "8000:8000"
    depends_on:
    - db
    restart: always
  db:
   image: absolutapps/oracle-12c-ee
   volumes:
     - ./libs/listener.ora:/u01/app/oracle-product/12.1.0.2/dbhome_1/network/admin/listener.ora
   restart: always


