version: '2'
services:
 electron:
   image: vulhub/electron:windows-builder
   command: bash -c 'cd /project && npm install && npm build-${ARCH}'
   volumes:
    - ./src:/project
   environment:
    - ARCH=64