version: '2'
services:
 nginx:
   image: nginx:1
   volumes:
    - ./www:/usr/share/nginx/html
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/sites-enabled:/etc/nginx/sites-enabled
   depends_on:
    - php
   ports:
    - "80:80"
    - "443:443"
 php:
   image: php:fpm 
   volumes:
    - ./www:/var/www/html
    - ./php-fpm/www-2.conf:/usr/local/etc/php-fpm.d/www-2.conf