version: '2'
services:
 web:
   build: .
   volumes:
    - ./cgi-bin:/usr/local/apache2/cgi-bin
    - ./start.sh:/usr/local/bin/start.sh
   command: /bin/sh /usr/local/bin/start.sh
   ports:
    - "80:80"