version: '2'
services:
 server:
   image: vulhub/zabbix:3.0.3-server
   depends_on:
    - mysql
   environment: 
    - DATABASE_HOST=mysql
    - DATABASE_PORT=3306
    - DATABASE_USER=root
    - DATABASE_PASS=root
    - DATABASE_NAME=wordpress
 mysql:
   image: mysql:5
   environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=zabbix
 web:
   image: vulhub/zabbix:3.0.3-web
   depends_on:
    - server
    - mysql
   environment:
    - DATABASE_HOST=mysql
    - DATABASE_PORT=3306
    - DATABASE_USER=root
    - DATABASE_PASS=root
    - DATABASE_NAME=wordpress
    - ZBX_SRV_HOST=server
    - ZBX_SRV_PORT=10051
   ports:
    - "8080:80"