version: '2'
services:
 web:
   build: .
   depends_on:
    - mysql
   ports:
    - "80:80"
   environment: 
    - DB_HOST=mysql
    - DB_PASS=root
 mysql:
   image: mysql:5
   environment: 
    - MYSQL_ROOT_PASSWORD=root
