version: '2'
services:
 web:
   build: .
   volumes:
    - .:/app
   ports:
    - "8000:8000"
   depends_on:
    - db 
   environment:
    - DATABASE_URL="postgres://postgres:postgres@db:5432/postgres"
 db:
   build: postgres
   environment:
    - POSTGRES_PASSWORD=postgres